name: referSystem
version: "${version}"
main: de.jonas.refersystem.ReferSystem
api-version: "1.21"
loader: de.jonas.refersystem.ReferSystemLoader
dependencies:
  server:
    Stuff:
      load: BEFORE
      required: true
      join-classpath: true
