name: referSystem
version: '${version}'
main: de.jonas.refersystem.ReferSystem
api-version: '1.20'
dependencies:
  server:
    Stuff:
      load: BEFORE
      required: true
      join-classpath: true